codecov:
  require_ci_to_pass: yes

coverage:
  range: 60..100
  round: down
  precision: 2

  status:
    project:                   # measuring the overall project coverage
      default:                 
        target: auto
        threshold: 0.01%

    patch:                    # measuring the coverage of new changes
      default:
        enabled: no


ignore:
  - "r/R/development_helpers.R"