{
  "R": {
    "Version": "4.2.2",
    "Repositories": [
      {
        "Name": "BioCsoft",
        "URL": "https://bioconductor.org/packages/3.15/bioc"
      },
      {
        "Name": "BioCann",
        "URL": "https://bioconductor.org/packages/3.15/data/annotation"
      },
      {
        "Name": "BioCexp",
        "URL": "https://bioconductor.org/packages/3.15/data/experiment"
      },
      {
        "Name": "BioCworkflows",
        "URL": "https://bioconductor.org/packages/3.15/workflows"
      },
      {
        "Name": "BioCbooks",
        "URL": "https://bioconductor.org/packages/3.15/books"
      },
      {
        "Name": "CRAN",
        "URL": "https://cloud.r-project.org"
      }
    ]
  },
  "Packages": {
    "BH": {
      "Package": "BH",
      "Version": "1.78.0-0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "4e348572ffcaa2fb1e610e7a941f6f3a",
      "Requirements": []
    },
    "Biobase": {
      "Package": "Biobase",
      "Version": "2.56.0",
      "Source": "Bioconductor",
      "git_url": "https://git.bioconductor.org/packages/Biobase",
      "git_branch": "RELEASE_3_15",
      "git_last_commit": "3b2dd91",
      "git_last_commit_date": "2022-04-26",
      "Hash": "b58c1eb25be406d1a35dd4cff0e9ba2e",
      "Requirements": [
        "BiocGenerics"
      ]
    },
    "BiocGenerics": {
      "Package": "BiocGenerics",
      "Version": "0.42.0",
      "Source": "Bioconductor",
      "git_url": "https://git.bioconductor.org/packages/BiocGenerics",
      "git_branch": "RELEASE_3_15",
      "git_last_commit": "3582d47",
      "git_last_commit_date": "2022-04-26",
      "Hash": "37348ee784e82c0a6b650146275b459d",
      "Requirements": []
    },
    "BiocManager": {
      "Package": "BiocManager",
      "Version": "1.30.19",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "726b3bc83ff8e0c35c7efdb74a462b0d",
      "Requirements": []
    },
    "BiocNeighbors": {
      "Package": "BiocNeighbors",
      "Version": "1.14.0",
      "Source": "Bioconductor",
      "git_url": "https://git.bioconductor.org/packages/BiocNeighbors",
      "git_branch": "RELEASE_3_15",
      "git_last_commit": "670a1bd",
      "git_last_commit_date": "2022-04-26",
      "Hash": "2892f03f485df26196566e41fa490211",
      "Requirements": [
        "BiocParallel",
        "Matrix",
        "Rcpp",
        "RcppHNSW",
        "S4Vectors"
      ]
    },
    "BiocParallel": {
      "Package": "BiocParallel",
      "Version": "1.30.4",
      "Source": "Bioconductor",
      "git_url": "https://git.bioconductor.org/packages/BiocParallel",
      "git_branch": "RELEASE_3_15",
      "git_last_commit": "3f8bbc2",
      "git_last_commit_date": "2022-10-11",
      "Hash": "979598ec1228a442839526dc8578be36",
      "Requirements": [
        "BH",
        "codetools",
        "futile.logger",
        "snow"
      ]
    },
    "BiocSingular": {
      "Package": "BiocSingular",
      "Version": "1.12.0",
      "Source": "Bioconductor",
      "git_url": "https://git.bioconductor.org/packages/BiocSingular",
      "git_branch": "RELEASE_3_15",
      "git_last_commit": "7d1b8f4",
      "git_last_commit_date": "2022-04-26",
      "Hash": "33c264615f520d023d83d68880a853b8",
      "Requirements": [
        "BiocGenerics",
        "BiocParallel",
        "DelayedArray",
        "Matrix",
        "Rcpp",
        "S4Vectors",
        "ScaledMatrix",
        "beachmat",
        "irlba",
        "rsvd"
      ]
    },
    "BiocVersion": {
      "Package": "BiocVersion",
      "Version": "3.15.2",
      "Source": "Bioconductor",
      "git_url": "https://git.bioconductor.org/packages/BiocVersion",
      "git_branch": "master",
      "git_last_commit": "818ab03",
      "git_last_commit_date": "2022-03-29",
      "Hash": "48e545a2fa24a967de72b1114bfe96ac",
      "Requirements": []
    },
    "Cairo": {
      "Package": "Cairo",
      "Version": "1.6-0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "60aada7beac23aa3e9b219485d6b2da8",
      "Requirements": []
    },
    "DBI": {
      "Package": "DBI",
      "Version": "1.1.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "b2866e62bab9378c3cc9476a1954226b",
      "Requirements": []
    },
    "DelayedArray": {
      "Package": "DelayedArray",
      "Version": "0.22.0",
      "Source": "Bioconductor",
      "git_url": "https://git.bioconductor.org/packages/DelayedArray",
      "git_branch": "RELEASE_3_15",
      "git_last_commit": "4a5afd1",
      "git_last_commit_date": "2022-04-26",
      "Hash": "c83a6e282a9669d4e04eb2d2ce8660a8",
      "Requirements": [
        "BiocGenerics",
        "IRanges",
        "Matrix",
        "MatrixGenerics",
        "S4Vectors"
      ]
    },
    "DelayedMatrixStats": {
      "Package": "DelayedMatrixStats",
      "Version": "1.18.2",
      "Source": "Bioconductor",
      "git_url": "https://git.bioconductor.org/packages/DelayedMatrixStats",
      "git_branch": "RELEASE_3_15",
      "git_last_commit": "694fc89",
      "git_last_commit_date": "2022-10-11",
      "Hash": "32ed3c5d3168e52088b0d39da58d3a62",
      "Requirements": [
        "DelayedArray",
        "IRanges",
        "Matrix",
        "MatrixGenerics",
        "S4Vectors",
        "matrixStats",
        "sparseMatrixStats"
      ]
    },
    "FNN": {
      "Package": "FNN",
      "Version": "1.1.3.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "a774898dbc05ccf03ed4ca93fa7a71f4",
      "Requirements": []
    },
    "GenomeInfoDb": {
      "Package": "GenomeInfoDb",
      "Version": "1.32.4",
      "Source": "Bioconductor",
      "git_url": "https://git.bioconductor.org/packages/GenomeInfoDb",
      "git_branch": "RELEASE_3_15",
      "git_last_commit": "69df6a5",
      "git_last_commit_date": "2022-09-06",
      "Hash": "45eeade5241cbc976f2114f62b90d81d",
      "Requirements": [
        "BiocGenerics",
        "GenomeInfoDbData",
        "IRanges",
        "RCurl",
        "S4Vectors"
      ]
    },
    "GenomeInfoDbData": {
      "Package": "GenomeInfoDbData",
      "Version": "1.2.8",
      "Source": "Bioconductor",
      "Hash": "b0e605ca22c2a5c6a65a3960729462da",
      "Requirements": []
    },
    "GenomicRanges": {
      "Package": "GenomicRanges",
      "Version": "1.48.0",
      "Source": "Bioconductor",
      "git_url": "https://git.bioconductor.org/packages/GenomicRanges",
      "git_branch": "RELEASE_3_15",
      "git_last_commit": "2bce608",
      "git_last_commit_date": "2022-04-26",
      "Hash": "07625db342974bca20a6d82dfc34386d",
      "Requirements": [
        "BiocGenerics",
        "GenomeInfoDb",
        "IRanges",
        "S4Vectors",
        "XVector"
      ]
    },
    "HDF5Array": {
      "Package": "HDF5Array",
      "Version": "1.24.2",
      "Source": "Bioconductor",
      "git_url": "https://git.bioconductor.org/packages/HDF5Array",
      "git_branch": "RELEASE_3_15",
      "git_last_commit": "fb213ba",
      "git_last_commit_date": "2022-08-01",
      "Hash": "13693baafc480c1bb4005fe6f5e4172f",
      "Requirements": [
        "BiocGenerics",
        "DelayedArray",
        "IRanges",
        "Matrix",
        "Rhdf5lib",
        "S4Vectors",
        "rhdf5",
        "rhdf5filters"
      ]
    },
    "IRanges": {
      "Package": "IRanges",
      "Version": "2.30.1",
      "Source": "Bioconductor",
      "git_url": "https://git.bioconductor.org/packages/IRanges",
      "git_branch": "RELEASE_3_15",
      "git_last_commit": "ead506a",
      "git_last_commit_date": "2022-08-17",
      "Hash": "98cde49c4d8c69377a05cf9a81053254",
      "Requirements": [
        "BiocGenerics",
        "S4Vectors"
      ]
    },
    "KernSmooth": {
      "Package": "KernSmooth",
      "Version": "2.23-20",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "8dcfa99b14c296bc9f1fd64d52fd3ce7",
      "Requirements": []
    },
    "MASS": {
      "Package": "MASS",
      "Version": "7.3-58.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "762e1804143a332333c054759f89a706",
      "Requirements": []
    },
    "Matrix": {
      "Package": "Matrix",
      "Version": "1.5-3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "4006dffe49958d2dd591c17e61e60591",
      "Requirements": [
        "lattice"
      ]
    },
    "Matrix.utils": {
      "Package": "Matrix.utils",
      "Version": "0.9.8",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "74d1586cef483fdd0703316240ed8c1e",
      "Requirements": [
        "Matrix",
        "grr"
      ]
    },
    "MatrixGenerics": {
      "Package": "MatrixGenerics",
      "Version": "1.8.1",
      "Source": "Bioconductor",
      "git_url": "https://git.bioconductor.org/packages/MatrixGenerics",
      "git_branch": "RELEASE_3_15",
      "git_last_commit": "a4a2108",
      "git_last_commit_date": "2022-06-23",
      "Hash": "0b6a466982071e55981cf5dd8d1c3ceb",
      "Requirements": [
        "matrixStats"
      ]
    },
    "R.methodsS3": {
      "Package": "R.methodsS3",
      "Version": "1.8.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "278c286fd6e9e75d0c2e8f731ea445c8",
      "Requirements": []
    },
    "R.oo": {
      "Package": "R.oo",
      "Version": "1.25.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "a0900a114f4f0194cf4aa8cd4a700681",
      "Requirements": [
        "R.methodsS3"
      ]
    },
    "R.utils": {
      "Package": "R.utils",
      "Version": "2.12.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "325f01db13da12c04d8f6e7be36ff514",
      "Requirements": [
        "R.methodsS3",
        "R.oo"
      ]
    },
    "R6": {
      "Package": "R6",
      "Version": "2.5.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "470851b6d5d0ac559e9d01bb352b4021",
      "Requirements": []
    },
    "RANN": {
      "Package": "RANN",
      "Version": "2.6.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "d128ea05a972d3e67c6f39de52c72bd7",
      "Requirements": []
    },
    "RColorBrewer": {
      "Package": "RColorBrewer",
      "Version": "1.1-3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "45f0398006e83a5b10b72a90663d8d8c",
      "Requirements": []
    },
    "RCurl": {
      "Package": "RCurl",
      "Version": "1.98-1.9",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "ea2f19dade6bd911b29b9bbb115d08f6",
      "Requirements": [
        "bitops"
      ]
    },
    "RJSONIO": {
      "Package": "RJSONIO",
      "Version": "1.3-1.6",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "0c7658433758cea5bcae50edd02b55b7",
      "Requirements": []
    },
    "ROCR": {
      "Package": "ROCR",
      "Version": "1.0-11",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "cc151930e20e16427bc3d0daec62b4a9",
      "Requirements": [
        "gplots"
      ]
    },
    "Rcpp": {
      "Package": "Rcpp",
      "Version": "1.0.9",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "e9c08b94391e9f3f97355841229124f2",
      "Requirements": []
    },
    "RcppAnnoy": {
      "Package": "RcppAnnoy",
      "Version": "0.0.20",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "0ad7d4b7e506364457d624c8353e1e4e",
      "Requirements": [
        "Rcpp"
      ]
    },
    "RcppArmadillo": {
      "Package": "RcppArmadillo",
      "Version": "0.11.4.2.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "5fa867879a70ed6df6ae4ed7f392fba2",
      "Requirements": [
        "Rcpp"
      ]
    },
    "RcppEigen": {
      "Package": "RcppEigen",
      "Version": "0.3.3.9.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "1e035db628cefb315c571202d70202fe",
      "Requirements": [
        "Matrix",
        "Rcpp"
      ]
    },
    "RcppHNSW": {
      "Package": "RcppHNSW",
      "Version": "0.4.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "a3fd7fda39fec57a7086b4fb9fa8aba3",
      "Requirements": [
        "Rcpp"
      ]
    },
    "RcppProgress": {
      "Package": "RcppProgress",
      "Version": "0.4.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "1c0aa18b97e6aaa17f93b8b866c0ace5",
      "Requirements": []
    },
    "RcppTOML": {
      "Package": "RcppTOML",
      "Version": "0.1.7",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "f8a578aa91321ecec1292f1e2ffadeda",
      "Requirements": [
        "Rcpp"
      ]
    },
    "ResidualMatrix": {
      "Package": "ResidualMatrix",
      "Version": "1.6.1",
      "Source": "Bioconductor",
      "git_url": "https://git.bioconductor.org/packages/ResidualMatrix",
      "git_branch": "RELEASE_3_15",
      "git_last_commit": "5a36715",
      "git_last_commit_date": "2022-08-16",
      "Hash": "d35c86acff9d2825b75074d979da2011",
      "Requirements": [
        "DelayedArray",
        "Matrix",
        "S4Vectors"
      ]
    },
    "RestRserve": {
      "Package": "RestRserve",
      "Version": "1.2.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "057e0424213a72c7b93543d8be6a1aec",
      "Requirements": [
        "R6",
        "Rcpp",
        "Rserve",
        "checkmate",
        "digest",
        "jsonlite",
        "mime",
        "uuid"
      ]
    },
    "Rhdf5lib": {
      "Package": "Rhdf5lib",
      "Version": "1.18.2",
      "Source": "Bioconductor",
      "git_url": "https://git.bioconductor.org/packages/Rhdf5lib",
      "git_branch": "RELEASE_3_15",
      "git_last_commit": "d104bbf",
      "git_last_commit_date": "2022-05-12",
      "Hash": "2958e31b9b8ea852e487bcb3c24b5b09",
      "Requirements": []
    },
    "RhpcBLASctl": {
      "Package": "RhpcBLASctl",
      "Version": "0.21-247.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "e0d1744b1339290bce02b1699230b8b5",
      "Requirements": []
    },
    "Rserve": {
      "Package": "Rserve",
      "Version": "1.8-11",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "ec79ee5ad4b315264e303e1df49aff64",
      "Requirements": []
    },
    "Rtsne": {
      "Package": "Rtsne",
      "Version": "0.16",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "e921b89ef921905fc89b95886675706d",
      "Requirements": [
        "Rcpp"
      ]
    },
    "S4Vectors": {
      "Package": "S4Vectors",
      "Version": "0.34.0",
      "Source": "Bioconductor",
      "git_url": "https://git.bioconductor.org/packages/S4Vectors",
      "git_branch": "RELEASE_3_15",
      "git_last_commit": "f590de3",
      "git_last_commit_date": "2022-04-26",
      "Hash": "90677cc888563927cecacd4067ccad45",
      "Requirements": [
        "BiocGenerics"
      ]
    },
    "ScaledMatrix": {
      "Package": "ScaledMatrix",
      "Version": "1.4.1",
      "Source": "Bioconductor",
      "git_url": "https://git.bioconductor.org/packages/ScaledMatrix",
      "git_branch": "RELEASE_3_15",
      "git_last_commit": "15e2efc",
      "git_last_commit_date": "2022-09-08",
      "Hash": "fa0a0785dd41ab4775bb5bd50937b5e6",
      "Requirements": [
        "DelayedArray",
        "Matrix",
        "S4Vectors"
      ]
    },
    "Seurat": {
      "Package": "Seurat",
      "Version": "4.3.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "5113e4493742aaf7727439e4b47c8e9d",
      "Requirements": [
        "KernSmooth",
        "MASS",
        "Matrix",
        "RANN",
        "RColorBrewer",
        "ROCR",
        "Rcpp",
        "RcppAnnoy",
        "RcppEigen",
        "RcppProgress",
        "Rtsne",
        "SeuratObject",
        "cluster",
        "cowplot",
        "fitdistrplus",
        "future",
        "future.apply",
        "ggplot2",
        "ggrepel",
        "ggridges",
        "httr",
        "ica",
        "igraph",
        "irlba",
        "jsonlite",
        "leiden",
        "lmtest",
        "matrixStats",
        "miniUI",
        "patchwork",
        "pbapply",
        "plotly",
        "png",
        "progressr",
        "reticulate",
        "rlang",
        "scales",
        "scattermore",
        "sctransform",
        "shiny",
        "spatstat.explore",
        "spatstat.geom",
        "tibble",
        "uwot"
      ]
    },
    "SeuratObject": {
      "Package": "SeuratObject",
      "Version": "4.1.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "31a87fa60eee00965ec7b5a5f56869b0",
      "Requirements": [
        "Matrix",
        "Rcpp",
        "RcppEigen",
        "future",
        "future.apply",
        "progressr",
        "rlang",
        "sp"
      ]
    },
    "SeuratWrappers": {
      "Package": "SeuratWrappers",
      "Version": "0.3.1",
      "Source": "GitHub",
      "RemoteType": "github",
      "RemoteUsername": "satijalab",
      "RemoteRepo": "seurat-wrappers",
      "RemoteRef": "master",
      "RemoteSha": "d28512f804d5fe05e6d68900ca9221020d52cf1d",
      "RemoteHost": "api.github.com",
      "Remotes": "welch-lab/liger, hms-dbmi/conos, immunogenomics/harmony,\n    immunogenomics/presto, satijalab/seurat-data, velocyto-team/velocyto.R,\n    SaskiaFreytag/schex@031320d, cole-trapnell-lab/monocle3,\n    mojaveazure/seurat-disk, powellgenomicslab/Nebulosa,\n    atakanekiz/CIPR-Package, prabhakarlab/Banksy",
      "Hash": "5e858d3d660cc273c1717c1774a31f85",
      "Requirements": [
        "BiocManager",
        "Matrix",
        "Seurat",
        "cowplot",
        "ggplot2",
        "igraph",
        "remotes",
        "rlang",
        "rsvd"
      ]
    },
    "SingleCellExperiment": {
      "Package": "SingleCellExperiment",
      "Version": "1.18.1",
      "Source": "Bioconductor",
      "git_url": "https://git.bioconductor.org/packages/SingleCellExperiment",
      "git_branch": "RELEASE_3_15",
      "git_last_commit": "db7768a",
      "git_last_commit_date": "2022-09-30",
      "Hash": "4c46104c0ed7a1650ee2e386e8dcbc1f",
      "Requirements": [
        "BiocGenerics",
        "DelayedArray",
        "GenomicRanges",
        "S4Vectors",
        "SummarizedExperiment"
      ]
    },
    "SummarizedExperiment": {
      "Package": "SummarizedExperiment",
      "Version": "1.26.1",
      "Source": "Bioconductor",
      "git_url": "https://git.bioconductor.org/packages/SummarizedExperiment",
      "git_branch": "RELEASE_3_15",
      "git_last_commit": "c8cbd3b",
      "git_last_commit_date": "2022-04-28",
      "Hash": "7cbcf1fe7236f18f1a961877fbf2d78c",
      "Requirements": [
        "Biobase",
        "BiocGenerics",
        "DelayedArray",
        "GenomeInfoDb",
        "GenomicRanges",
        "IRanges",
        "Matrix",
        "MatrixGenerics",
        "S4Vectors"
      ]
    },
    "XVector": {
      "Package": "XVector",
      "Version": "0.36.0",
      "Source": "Bioconductor",
      "git_url": "https://git.bioconductor.org/packages/XVector",
      "git_branch": "RELEASE_3_15",
      "git_last_commit": "ff6f818",
      "git_last_commit_date": "2022-04-26",
      "Hash": "03b87ac645463f29d04c2461d5de9610",
      "Requirements": [
        "BiocGenerics",
        "IRanges",
        "S4Vectors",
        "zlibbioc"
      ]
    },
    "abind": {
      "Package": "abind",
      "Version": "1.4-5",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "4f57884290cc75ab22f4af9e9d4ca862",
      "Requirements": []
    },
    "askpass": {
      "Package": "askpass",
      "Version": "1.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "e8a22846fff485f0be3770c2da758713",
      "Requirements": [
        "sys"
      ]
    },
    "assertthat": {
      "Package": "assertthat",
      "Version": "0.2.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "50c838a310445e954bc13f26f26a6ecf",
      "Requirements": []
    },
    "backports": {
      "Package": "backports",
      "Version": "1.4.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "c39fbec8a30d23e721980b8afb31984c",
      "Requirements": []
    },
    "base64enc": {
      "Package": "base64enc",
      "Version": "0.1-3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "543776ae6848fde2f48ff3816d0628bc",
      "Requirements": []
    },
    "batchelor": {
      "Package": "batchelor",
      "Version": "1.12.3",
      "Source": "Bioconductor",
      "git_url": "https://git.bioconductor.org/packages/batchelor",
      "git_branch": "RELEASE_3_15",
      "git_last_commit": "94788f9",
      "git_last_commit_date": "2022-06-22",
      "Hash": "f03c96a4e54ce90fcdf4c7354e4c83a6",
      "Requirements": [
        "BiocGenerics",
        "BiocNeighbors",
        "BiocParallel",
        "BiocSingular",
        "DelayedArray",
        "DelayedMatrixStats",
        "Matrix",
        "Rcpp",
        "ResidualMatrix",
        "S4Vectors",
        "ScaledMatrix",
        "SingleCellExperiment",
        "SummarizedExperiment",
        "beachmat",
        "igraph",
        "scuttle"
      ]
    },
    "beachmat": {
      "Package": "beachmat",
      "Version": "2.12.0",
      "Source": "Bioconductor",
      "git_url": "https://git.bioconductor.org/packages/beachmat",
      "git_branch": "RELEASE_3_15",
      "git_last_commit": "3e6af14",
      "git_last_commit_date": "2022-04-26",
      "Hash": "2a52023b7b17fb9600abe3243b796470",
      "Requirements": [
        "BiocGenerics",
        "DelayedArray",
        "Matrix",
        "Rcpp"
      ]
    },
    "beeswarm": {
      "Package": "beeswarm",
      "Version": "0.4.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "0f4e9d8caa6feaa7e409ae6c30f2ca66",
      "Requirements": []
    },
    "bit": {
      "Package": "bit",
      "Version": "4.0.5",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "d242abec29412ce988848d0294b208fd",
      "Requirements": []
    },
    "bit64": {
      "Package": "bit64",
      "Version": "4.0.5",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "9fe98599ca456d6552421db0d6772d8f",
      "Requirements": [
        "bit"
      ]
    },
    "bitops": {
      "Package": "bitops",
      "Version": "1.0-7",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "b7d8d8ee39869c18d8846a184dd8a1af",
      "Requirements": []
    },
    "boot": {
      "Package": "boot",
      "Version": "1.3-28.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "9a052fbcbe97a98ceb18dbfd30ebd96e",
      "Requirements": []
    },
    "brio": {
      "Package": "brio",
      "Version": "1.1.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "976cf154dfb043c012d87cddd8bca363",
      "Requirements": []
    },
    "bslib": {
      "Package": "bslib",
      "Version": "0.4.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "a7fbf03946ad741129dc81098722fca1",
      "Requirements": [
        "base64enc",
        "cachem",
        "htmltools",
        "jquerylib",
        "jsonlite",
        "memoise",
        "mime",
        "rlang",
        "sass"
      ]
    },
    "caTools": {
      "Package": "caTools",
      "Version": "1.18.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "34d90fa5845004236b9eacafc51d07b2",
      "Requirements": [
        "bitops"
      ]
    },
    "cachem": {
      "Package": "cachem",
      "Version": "1.0.6",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "648c5b3d71e6a37e3043617489a0a0e9",
      "Requirements": [
        "fastmap",
        "rlang"
      ]
    },
    "callr": {
      "Package": "callr",
      "Version": "3.7.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "9b2191ede20fa29828139b9900922e51",
      "Requirements": [
        "R6",
        "processx"
      ]
    },
    "checkmate": {
      "Package": "checkmate",
      "Version": "2.1.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "147e4db6909d8814bb30f671b49d7e06",
      "Requirements": [
        "backports"
      ]
    },
    "class": {
      "Package": "class",
      "Version": "7.3-20",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "da09d82223e669d270e47ed24ac8686e",
      "Requirements": [
        "MASS"
      ]
    },
    "classInt": {
      "Package": "classInt",
      "Version": "0.4-8",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "298fa500d773db0845935cd73bfd9c2e",
      "Requirements": [
        "KernSmooth",
        "class",
        "e1071"
      ]
    },
    "cli": {
      "Package": "cli",
      "Version": "3.5.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "eb9fc121ad9a1075c471107ef185be46",
      "Requirements": []
    },
    "cluster": {
      "Package": "cluster",
      "Version": "2.1.4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "5edbbabab6ce0bf7900a74fd4358628e",
      "Requirements": []
    },
    "codetools": {
      "Package": "codetools",
      "Version": "0.2-18",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "019388fc48e48b3da0d3a76ff94608a8",
      "Requirements": []
    },
    "colorspace": {
      "Package": "colorspace",
      "Version": "2.0-3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "bb4341986bc8b914f0f0acf2e4a3f2f7",
      "Requirements": []
    },
    "commonmark": {
      "Package": "commonmark",
      "Version": "1.8.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "b6e3e947d1d7ebf3d2bdcea1bde63fe7",
      "Requirements": []
    },
    "covr": {
      "Package": "covr",
      "Version": "3.6.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "a861cee34fbb4b107a73dd414ef56724",
      "Requirements": [
        "crayon",
        "digest",
        "httr",
        "jsonlite",
        "rex",
        "withr",
        "yaml"
      ]
    },
    "cowplot": {
      "Package": "cowplot",
      "Version": "1.1.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "b418e8423699d11c7f2087c2bfd07da2",
      "Requirements": [
        "ggplot2",
        "gtable",
        "rlang",
        "scales"
      ]
    },
    "cpp11": {
      "Package": "cpp11",
      "Version": "0.4.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "ed588261931ee3be2c700d22e94a29ab",
      "Requirements": []
    },
    "crayon": {
      "Package": "crayon",
      "Version": "1.5.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "e8a1e41acf02548751f45c718d55aa6a",
      "Requirements": []
    },
    "crosstalk": {
      "Package": "crosstalk",
      "Version": "1.2.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "6aa54f69598c32177e920eb3402e8293",
      "Requirements": [
        "R6",
        "htmltools",
        "jsonlite",
        "lazyeval"
      ]
    },
    "curl": {
      "Package": "curl",
      "Version": "4.3.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "0eb86baa62f06e8855258fa5a8048667",
      "Requirements": []
    },
    "data.table": {
      "Package": "data.table",
      "Version": "1.14.6",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "aecef50008ea7b57c76f1cb5c127fb02",
      "Requirements": []
    },
    "deldir": {
      "Package": "deldir",
      "Version": "1.0-6",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "65a3d4e2a1619bb85ae0fb64628da972",
      "Requirements": []
    },
    "desc": {
      "Package": "desc",
      "Version": "1.4.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "6b9602c7ebbe87101a9c8edb6e8b6d21",
      "Requirements": [
        "R6",
        "cli",
        "rprojroot"
      ]
    },
    "diffobj": {
      "Package": "diffobj",
      "Version": "0.3.5",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "bcaa8b95f8d7d01a5dedfd959ce88ab8",
      "Requirements": [
        "crayon"
      ]
    },
    "digest": {
      "Package": "digest",
      "Version": "0.6.31",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "8b708f296afd9ae69f450f9640be8990",
      "Requirements": []
    },
    "dplyr": {
      "Package": "dplyr",
      "Version": "1.0.10",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "539412282059f7f0c07295723d23f987",
      "Requirements": [
        "R6",
        "generics",
        "glue",
        "lifecycle",
        "magrittr",
        "pillar",
        "rlang",
        "tibble",
        "tidyselect",
        "vctrs"
      ]
    },
    "dqrng": {
      "Package": "dqrng",
      "Version": "0.3.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "3ce2af5ead3b01c518fd453c7fe5a51a",
      "Requirements": [
        "BH",
        "Rcpp",
        "sitmo"
      ]
    },
    "e1071": {
      "Package": "e1071",
      "Version": "1.7-12",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "0d776df7577206e100c2c4b508208b10",
      "Requirements": [
        "class",
        "proxy"
      ]
    },
    "edgeR": {
      "Package": "edgeR",
      "Version": "3.38.4",
      "Source": "Bioconductor",
      "git_url": "https://git.bioconductor.org/packages/edgeR",
      "git_branch": "RELEASE_3_15",
      "git_last_commit": "f5a3bb5",
      "git_last_commit_date": "2022-08-07",
      "Hash": "690935220186be570df6673cf412ed31",
      "Requirements": [
        "Rcpp",
        "limma",
        "locfit"
      ]
    },
    "ellipsis": {
      "Package": "ellipsis",
      "Version": "0.3.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "bb0eec2fe32e88d9e2836c2f73ea2077",
      "Requirements": [
        "rlang"
      ]
    },
    "evaluate": {
      "Package": "evaluate",
      "Version": "0.19",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "5aac3cd0a3ccb1a738941796b28c26fe",
      "Requirements": []
    },
    "fansi": {
      "Package": "fansi",
      "Version": "1.0.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "83a8afdbe71839506baa9f90eebad7ec",
      "Requirements": []
    },
    "farver": {
      "Package": "farver",
      "Version": "2.1.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "8106d78941f34855c440ddb946b8f7a5",
      "Requirements": []
    },
    "fastmap": {
      "Package": "fastmap",
      "Version": "1.1.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "77bd60a6157420d4ffa93b27cf6a58b8",
      "Requirements": []
    },
    "fitdistrplus": {
      "Package": "fitdistrplus",
      "Version": "1.1-8",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "9de7bf56c16871adf44dc88a24c7836c",
      "Requirements": [
        "MASS",
        "survival"
      ]
    },
    "fontawesome": {
      "Package": "fontawesome",
      "Version": "0.4.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "c5a628c2570aa86a96cc6ef739d8bfda",
      "Requirements": [
        "htmltools",
        "rlang"
      ]
    },
    "foreign": {
      "Package": "foreign",
      "Version": "0.8-84",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "467ec0ca895d4e61a22cfbac9bccddf8",
      "Requirements": []
    },
    "formatR": {
      "Package": "formatR",
      "Version": "1.13",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "93a7b3306d291ae1116008e31fc114b5",
      "Requirements": []
    },
    "fs": {
      "Package": "fs",
      "Version": "1.5.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "7c89603d81793f0d5486d91ab1fc6f1d",
      "Requirements": []
    },
    "furrr": {
      "Package": "furrr",
      "Version": "0.3.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "da7a4c32196cb2262a41dd5a25d486ff",
      "Requirements": [
        "future",
        "globals",
        "lifecycle",
        "purrr",
        "rlang",
        "vctrs"
      ]
    },
    "futile.logger": {
      "Package": "futile.logger",
      "Version": "1.4.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "99f0ace8c05ec7d3683d27083c4f1e7e",
      "Requirements": [
        "futile.options",
        "lambda.r"
      ]
    },
    "futile.options": {
      "Package": "futile.options",
      "Version": "1.0.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "0d9bf02413ddc2bbe8da9ce369dcdd2b",
      "Requirements": []
    },
    "future": {
      "Package": "future",
      "Version": "1.30.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "d8a0dcbc9350c1e40edc644611d1ee15",
      "Requirements": [
        "digest",
        "globals",
        "listenv",
        "parallelly"
      ]
    },
    "future.apply": {
      "Package": "future.apply",
      "Version": "1.10.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "a930c9ddc317f898e6f5bed7be8dd322",
      "Requirements": [
        "future",
        "globals"
      ]
    },
    "generics": {
      "Package": "generics",
      "Version": "0.1.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "15e9634c0fcd294799e9b2e929ed1b86",
      "Requirements": []
    },
    "ggbeeswarm": {
      "Package": "ggbeeswarm",
      "Version": "0.7.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "e2adea988a575e168ad44022e80cd44e",
      "Requirements": [
        "beeswarm",
        "ggplot2",
        "lifecycle",
        "vipor"
      ]
    },
    "ggplot2": {
      "Package": "ggplot2",
      "Version": "3.4.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "fd2aab12f54400c6bca43687231e246b",
      "Requirements": [
        "MASS",
        "cli",
        "glue",
        "gtable",
        "isoband",
        "lifecycle",
        "mgcv",
        "rlang",
        "scales",
        "tibble",
        "vctrs",
        "withr"
      ]
    },
    "ggrastr": {
      "Package": "ggrastr",
      "Version": "1.0.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "8dabdab0c31adb630b6e0fabfdc0968d",
      "Requirements": [
        "Cairo",
        "ggbeeswarm",
        "ggplot2",
        "png",
        "ragg"
      ]
    },
    "ggrepel": {
      "Package": "ggrepel",
      "Version": "0.9.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "610af35a68a1e8a40f05aad45871e719",
      "Requirements": [
        "Rcpp",
        "ggplot2",
        "rlang",
        "scales"
      ]
    },
    "ggridges": {
      "Package": "ggridges",
      "Version": "0.5.4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "c76ee8fe60939384b9726128e38caea0",
      "Requirements": [
        "ggplot2",
        "scales",
        "withr"
      ]
    },
    "globals": {
      "Package": "globals",
      "Version": "0.16.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "baa9585ab4ce47a9f4618e671778cc6f",
      "Requirements": [
        "codetools"
      ]
    },
    "glue": {
      "Package": "glue",
      "Version": "1.6.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "4f2596dfb05dac67b9dc558e5c6fba2e",
      "Requirements": []
    },
    "goftest": {
      "Package": "goftest",
      "Version": "1.2-3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "dbe0201f91eeb15918dd3fbf01ee689a",
      "Requirements": []
    },
    "gplots": {
      "Package": "gplots",
      "Version": "3.1.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "75437dd4c43599f6e9418ea249495fda",
      "Requirements": [
        "KernSmooth",
        "caTools",
        "gtools"
      ]
    },
    "gridExtra": {
      "Package": "gridExtra",
      "Version": "2.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "7d7f283939f563670a697165b2cf5560",
      "Requirements": [
        "gtable"
      ]
    },
    "grr": {
      "Package": "grr",
      "Version": "0.9.5",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "195f3206842ea5ae11968e8d462bb828",
      "Requirements": []
    },
    "gtable": {
      "Package": "gtable",
      "Version": "0.3.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "36b4265fb818f6a342bed217549cd896",
      "Requirements": []
    },
    "gtools": {
      "Package": "gtools",
      "Version": "3.9.4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "88bb96eaf7140cdf29e374ef74182220",
      "Requirements": []
    },
    "here": {
      "Package": "here",
      "Version": "1.0.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "24b224366f9c2e7534d2344d10d59211",
      "Requirements": [
        "rprojroot"
      ]
    },
    "highr": {
      "Package": "highr",
      "Version": "0.10",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "06230136b2d2b9ba5805e1963fa6e890",
      "Requirements": [
        "xfun"
      ]
    },
    "hms": {
      "Package": "hms",
      "Version": "1.1.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "41100392191e1244b887878b533eea91",
      "Requirements": [
        "ellipsis",
        "lifecycle",
        "pkgconfig",
        "rlang",
        "vctrs"
      ]
    },
    "htmltools": {
      "Package": "htmltools",
      "Version": "0.5.4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "9d27e99cc90bd701c0a7a63e5923f9b7",
      "Requirements": [
        "base64enc",
        "digest",
        "ellipsis",
        "fastmap",
        "rlang"
      ]
    },
    "htmlwidgets": {
      "Package": "htmlwidgets",
      "Version": "1.6.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "f894e7b76e36258a483c602a786d7270",
      "Requirements": [
        "htmltools",
        "jsonlite",
        "knitr",
        "rmarkdown",
        "yaml"
      ]
    },
    "httptest": {
      "Package": "httptest",
      "Version": "4.1.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "cd910dc78e8edbc40b9723824baa7097",
      "Requirements": [
        "curl",
        "digest",
        "httr",
        "jsonlite",
        "testthat"
      ]
    },
    "httpuv": {
      "Package": "httpuv",
      "Version": "1.6.7",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "13fdc650c853fffbffee66b2a5b9fdbf",
      "Requirements": [
        "R6",
        "Rcpp",
        "later",
        "promises"
      ]
    },
    "httr": {
      "Package": "httr",
      "Version": "1.4.4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "57557fac46471f0dbbf44705cc6a5c8c",
      "Requirements": [
        "R6",
        "curl",
        "jsonlite",
        "mime",
        "openssl"
      ]
    },
    "ica": {
      "Package": "ica",
      "Version": "1.0-3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "d9b52ced14e24a0e69e228c20eb5eb27",
      "Requirements": []
    },
    "igraph": {
      "Package": "igraph",
      "Version": "1.3.5.9091",
      "Source": "GitHub",
      "RemoteType": "github",
      "RemoteUsername": "igraph",
      "RemoteRepo": "rigraph",
      "RemoteRef": "master",
      "RemoteSha": "80694f11430701d35ae906d7e826bfb044e45354",
      "RemoteHost": "api.github.com",
      "Hash": "5c8c9a980b84eb2f357b78c2de0057c6",
      "Requirements": [
        "Matrix",
        "magrittr",
        "pkgconfig",
        "rlang"
      ]
    },
    "irlba": {
      "Package": "irlba",
      "Version": "2.3.5.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "acb06a47b732c6251afd16e19c3201ff",
      "Requirements": [
        "Matrix"
      ]
    },
    "isoband": {
      "Package": "isoband",
      "Version": "0.2.7",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "0080607b4a1a7b28979aecef976d8bc2",
      "Requirements": []
    },
    "jquerylib": {
      "Package": "jquerylib",
      "Version": "0.1.4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "5aab57a3bd297eee1c1d862735972182",
      "Requirements": [
        "htmltools"
      ]
    },
    "jsonlite": {
      "Package": "jsonlite",
      "Version": "1.8.4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "a4269a09a9b865579b2635c77e572374",
      "Requirements": []
    },
    "knitr": {
      "Package": "knitr",
      "Version": "1.41",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "6d4971f3610e75220534a1befe81bc92",
      "Requirements": [
        "evaluate",
        "highr",
        "stringr",
        "xfun",
        "yaml"
      ]
    },
    "labeling": {
      "Package": "labeling",
      "Version": "0.4.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "3d5108641f47470611a32d0bdf357a72",
      "Requirements": []
    },
    "lambda.r": {
      "Package": "lambda.r",
      "Version": "1.2.4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "b1e925c4b9ffeb901bacf812cbe9a6ad",
      "Requirements": [
        "formatR"
      ]
    },
    "later": {
      "Package": "later",
      "Version": "1.3.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "7e7b457d7766bc47f2a5f21cc2984f8e",
      "Requirements": [
        "Rcpp",
        "rlang"
      ]
    },
    "lattice": {
      "Package": "lattice",
      "Version": "0.20-45",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "b64cdbb2b340437c4ee047a1f4c4377b",
      "Requirements": []
    },
    "lazyeval": {
      "Package": "lazyeval",
      "Version": "0.2.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "d908914ae53b04d4c0c0fd72ecc35370",
      "Requirements": []
    },
    "leiden": {
      "Package": "leiden",
      "Version": "0.4.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "3ddd87b156152001d3ab82979808af00",
      "Requirements": [
        "Matrix",
        "igraph",
        "reticulate"
      ]
    },
    "leidenbase": {
      "Package": "leidenbase",
      "Version": "0.1.14",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "91cba079c458260161a71699d1310b66",
      "Requirements": [
        "igraph"
      ]
    },
    "lifecycle": {
      "Package": "lifecycle",
      "Version": "1.0.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "001cecbeac1cff9301bdc3775ee46a86",
      "Requirements": [
        "cli",
        "glue",
        "rlang"
      ]
    },
    "limma": {
      "Package": "limma",
      "Version": "3.52.4",
      "Source": "Bioconductor",
      "git_url": "https://git.bioconductor.org/packages/limma",
      "git_branch": "RELEASE_3_15",
      "git_last_commit": "3226c29",
      "git_last_commit_date": "2022-09-26",
      "Hash": "89355064f134b79b47db214977a84d65",
      "Requirements": []
    },
    "listenv": {
      "Package": "listenv",
      "Version": "0.9.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "4fbd3679ec8ee169ba28d4b1ea7d0e8f",
      "Requirements": []
    },
    "lme4": {
      "Package": "lme4",
      "Version": "1.1-31",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "67581bdc21e3d5e6881cf47c0c3113eb",
      "Requirements": [
        "MASS",
        "Matrix",
        "Rcpp",
        "RcppEigen",
        "boot",
        "lattice",
        "minqa",
        "nlme",
        "nloptr"
      ]
    },
    "lmtest": {
      "Package": "lmtest",
      "Version": "0.9-40",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "c6fafa6cccb1e1dfe7f7d122efd6e6a7",
      "Requirements": [
        "zoo"
      ]
    },
    "locfit": {
      "Package": "locfit",
      "Version": "1.5-9.7",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "08c4156abea85c9b6d4e7798427a887d",
      "Requirements": [
        "lattice"
      ]
    },
    "magrittr": {
      "Package": "magrittr",
      "Version": "2.0.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "7ce2733a9826b3aeb1775d56fd305472",
      "Requirements": []
    },
    "maketools": {
      "Package": "maketools",
      "Version": "1.2.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "1621cb95007b3e1626bb5597c5faf799",
      "Requirements": [
        "sys"
      ]
    },
    "matrixStats": {
      "Package": "matrixStats",
      "Version": "0.63.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "57af0c3da1f1a50680b186591c3359af",
      "Requirements": []
    },
    "memoise": {
      "Package": "memoise",
      "Version": "2.0.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "e2817ccf4a065c5d9d7f2cfbe7c1d78c",
      "Requirements": [
        "cachem",
        "rlang"
      ]
    },
    "mgcv": {
      "Package": "mgcv",
      "Version": "1.8-41",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "6b3904f13346742caa3e82dd0303d4ad",
      "Requirements": [
        "Matrix",
        "nlme"
      ]
    },
    "mime": {
      "Package": "mime",
      "Version": "0.12",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "18e9c28c1d3ca1560ce30658b22ce104",
      "Requirements": []
    },
    "miniUI": {
      "Package": "miniUI",
      "Version": "0.1.1.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "fec5f52652d60615fdb3957b3d74324a",
      "Requirements": [
        "htmltools",
        "shiny"
      ]
    },
    "minqa": {
      "Package": "minqa",
      "Version": "1.2.5",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "587ce77fd3c7bada7eadb2d18b62930d",
      "Requirements": [
        "Rcpp"
      ]
    },
    "mockery": {
      "Package": "mockery",
      "Version": "0.4.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "c28ce5f7c2293d76b91657f3fe30c50b",
      "Requirements": [
        "testthat"
      ]
    },
    "monocle3": {
      "Package": "monocle3",
      "Version": "1.3.1",
      "Source": "GitHub",
      "RemoteType": "github",
      "RemoteUsername": "cole-trapnell-lab",
      "RemoteRepo": "monocle3",
      "RemoteRef": "master",
      "RemoteSha": "b545460966874948eb11a57a225594a107f1694d",
      "RemoteHost": "api.github.com",
      "Hash": "ac8e5391abf4fe7614fc4c1adf291735",
      "Requirements": [
        "Biobase",
        "BiocGenerics",
        "BiocParallel",
        "DelayedArray",
        "DelayedMatrixStats",
        "HDF5Array",
        "MASS",
        "Matrix",
        "RANN",
        "RColorBrewer",
        "Rcpp",
        "RcppAnnoy",
        "RcppHNSW",
        "RhpcBLASctl",
        "Rtsne",
        "S4Vectors",
        "SingleCellExperiment",
        "SummarizedExperiment",
        "assertthat",
        "batchelor",
        "digest",
        "dplyr",
        "future",
        "ggplot2",
        "ggrastr",
        "ggrepel",
        "grr",
        "igraph",
        "irlba",
        "leidenbase",
        "limma",
        "lme4",
        "lmtest",
        "openssl",
        "pbapply",
        "pbmcapply",
        "pheatmap",
        "plotly",
        "plyr",
        "proxy",
        "pscl",
        "purrr",
        "reshape2",
        "rsample",
        "shiny",
        "slam",
        "spdep",
        "speedglm",
        "stringr",
        "terra",
        "tibble",
        "tidyr",
        "uwot",
        "viridis"
      ]
    },
    "munsell": {
      "Package": "munsell",
      "Version": "0.5.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "6dfe8bf774944bd5595785e3229d8771",
      "Requirements": [
        "colorspace"
      ]
    },
    "nlme": {
      "Package": "nlme",
      "Version": "3.1-161",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "b49e163093c0ef46fbbfc40bcb87916c",
      "Requirements": [
        "lattice"
      ]
    },
    "nloptr": {
      "Package": "nloptr",
      "Version": "2.0.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "277c67a08f358f42b6a77826e4492f79",
      "Requirements": [
        "testthat"
      ]
    },
    "nnet": {
      "Package": "nnet",
      "Version": "7.3-18",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "170da2130d5332bea7d6ede01875ba1d",
      "Requirements": []
    },
    "openssl": {
      "Package": "openssl",
      "Version": "2.0.5",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "b04c27110bf367b4daa93f34f3d58e75",
      "Requirements": [
        "askpass"
      ]
    },
    "parallelly": {
      "Package": "parallelly",
      "Version": "1.33.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "6d5c4a319b25b6df4600af95817ffbd5",
      "Requirements": []
    },
    "patchwork": {
      "Package": "patchwork",
      "Version": "1.1.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "63b611e9d909a9ed057639d9c3b77152",
      "Requirements": [
        "ggplot2",
        "gtable"
      ]
    },
    "pbapply": {
      "Package": "pbapply",
      "Version": "1.6-0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "77caedbd6227e10924d1ed2eaa3d53ce",
      "Requirements": []
    },
    "pbmcapply": {
      "Package": "pbmcapply",
      "Version": "1.5.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "bf173fb42b60f8f404f7a9f9c3f95d0d",
      "Requirements": []
    },
    "pheatmap": {
      "Package": "pheatmap",
      "Version": "1.0.12",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "db1fb0021811b6693741325bbe916e58",
      "Requirements": [
        "RColorBrewer",
        "gtable",
        "scales"
      ]
    },
    "pillar": {
      "Package": "pillar",
      "Version": "1.8.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "f2316df30902c81729ae9de95ad5a608",
      "Requirements": [
        "cli",
        "fansi",
        "glue",
        "lifecycle",
        "rlang",
        "utf8",
        "vctrs"
      ]
    },
    "pkgconfig": {
      "Package": "pkgconfig",
      "Version": "2.0.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "01f28d4278f15c76cddbea05899c5d6f",
      "Requirements": []
    },
    "pkgload": {
      "Package": "pkgload",
      "Version": "1.3.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "6b0c222c5071efe0f3baf3dae9aa40e2",
      "Requirements": [
        "cli",
        "crayon",
        "desc",
        "fs",
        "glue",
        "rlang",
        "rprojroot",
        "withr"
      ]
    },
    "plotly": {
      "Package": "plotly",
      "Version": "4.10.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "3781cf6971c6467fa842a63725bbee9e",
      "Requirements": [
        "RColorBrewer",
        "base64enc",
        "crosstalk",
        "data.table",
        "digest",
        "dplyr",
        "ggplot2",
        "htmltools",
        "htmlwidgets",
        "httr",
        "jsonlite",
        "lazyeval",
        "magrittr",
        "promises",
        "purrr",
        "rlang",
        "scales",
        "tibble",
        "tidyr",
        "vctrs",
        "viridisLite"
      ]
    },
    "plyr": {
      "Package": "plyr",
      "Version": "1.8.8",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "d744387aef9047b0b48be2933d78e862",
      "Requirements": [
        "Rcpp"
      ]
    },
    "png": {
      "Package": "png",
      "Version": "0.1-8",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "bd54ba8a0a5faded999a7aab6e46b374",
      "Requirements": []
    },
    "polyclip": {
      "Package": "polyclip",
      "Version": "1.10-4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "66bbfa06f78108ee967220643596c91e",
      "Requirements": []
    },
    "praise": {
      "Package": "praise",
      "Version": "1.0.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "a555924add98c99d2f411e37e7d25e9f",
      "Requirements": []
    },
    "presto": {
      "Package": "presto",
      "Version": "1.0.0",
      "Source": "GitHub",
      "RemoteType": "github",
      "RemoteUsername": "immunogenomics",
      "RemoteRepo": "presto",
      "RemoteRef": "master",
      "RemoteSha": "045390ae5b9e388971c1381018be87fa3eb34604",
      "RemoteHost": "api.github.com",
      "Hash": "d158445cb10e521d04a3848a0de1a9da",
      "Requirements": [
        "Matrix",
        "Rcpp",
        "RcppArmadillo",
        "data.table",
        "dplyr",
        "purrr",
        "rlang",
        "tibble",
        "tidyr"
      ]
    },
    "prettyunits": {
      "Package": "prettyunits",
      "Version": "1.1.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "95ef9167b75dde9d2ccc3c7528393e7e",
      "Requirements": []
    },
    "processx": {
      "Package": "processx",
      "Version": "3.8.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "a33ee2d9bf07564efb888ad98410da84",
      "Requirements": [
        "R6",
        "ps"
      ]
    },
    "progress": {
      "Package": "progress",
      "Version": "1.2.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "14dc9f7a3c91ebb14ec5bb9208a07061",
      "Requirements": [
        "R6",
        "crayon",
        "hms",
        "prettyunits"
      ]
    },
    "progressr": {
      "Package": "progressr",
      "Version": "0.12.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "e59a5a5d07c56229458c3374951cb8d0",
      "Requirements": [
        "digest"
      ]
    },
    "promises": {
      "Package": "promises",
      "Version": "1.2.0.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "4ab2c43adb4d4699cf3690acd378d75d",
      "Requirements": [
        "R6",
        "Rcpp",
        "later",
        "magrittr",
        "rlang"
      ]
    },
    "proxy": {
      "Package": "proxy",
      "Version": "0.4-27",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "e0ef355c12942cf7a6b91a6cfaea8b3e",
      "Requirements": []
    },
    "ps": {
      "Package": "ps",
      "Version": "1.7.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "68dd03d98a5efd1eb3012436de45ba83",
      "Requirements": []
    },
    "pscl": {
      "Package": "pscl",
      "Version": "1.5.5",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "c55158537b8c4754a8c3de3382f1a659",
      "Requirements": [
        "MASS"
      ]
    },
    "purrr": {
      "Package": "purrr",
      "Version": "1.0.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "1ad491d27989ec6c26a2918ad6df116b",
      "Requirements": [
        "cli",
        "lifecycle",
        "magrittr",
        "rlang",
        "vctrs"
      ]
    },
    "ragg": {
      "Package": "ragg",
      "Version": "1.2.4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "0db17bd5a1d4abfec76487b6f5dd957b",
      "Requirements": [
        "systemfonts",
        "textshaping"
      ]
    },
    "rappdirs": {
      "Package": "rappdirs",
      "Version": "0.3.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "5e3c5dc0b071b21fa128676560dbe94d",
      "Requirements": []
    },
    "rematch2": {
      "Package": "rematch2",
      "Version": "2.1.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "76c9e04c712a05848ae7a23d2f170a40",
      "Requirements": [
        "tibble"
      ]
    },
    "remotes": {
      "Package": "remotes",
      "Version": "2.4.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "227045be9aee47e6dda9bb38ac870d67",
      "Requirements": []
    },
    "renv": {
      "Package": "renv",
      "Version": "0.16.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "c9e8442ab69bc21c9697ecf856c1e6c7",
      "Requirements": []
    },
    "reshape2": {
      "Package": "reshape2",
      "Version": "1.4.4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "bb5996d0bd962d214a11140d77589917",
      "Requirements": [
        "Rcpp",
        "plyr",
        "stringr"
      ]
    },
    "reticulate": {
      "Package": "reticulate",
      "Version": "1.26-9000",
      "Source": "GitHub",
      "RemoteType": "github",
      "RemoteHost": "api.github.com",
      "RemoteUsername": "rstudio",
      "RemoteRepo": "reticulate",
      "RemoteRef": "29c84d5631545911a678c3d515d4557c7b85d89e",
      "RemoteSha": "29c84d5631545911a678c3d515d4557c7b85d89e",
      "Hash": "1fbd16fb844017519cdede66bc95a5a2",
      "Requirements": [
        "Matrix",
        "Rcpp",
        "RcppTOML",
        "here",
        "jsonlite",
        "png",
        "rappdirs",
        "withr"
      ]
    },
    "rex": {
      "Package": "rex",
      "Version": "1.2.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "ae34cd56890607370665bee5bd17812f",
      "Requirements": [
        "lazyeval"
      ]
    },
    "rhdf5": {
      "Package": "rhdf5",
      "Version": "2.40.0",
      "Source": "Bioconductor",
      "git_url": "https://git.bioconductor.org/packages/rhdf5",
      "git_branch": "RELEASE_3_15",
      "git_last_commit": "fb6c15a",
      "git_last_commit_date": "2022-04-26",
      "Hash": "46690d82f3e32c11679919456785c42c",
      "Requirements": [
        "Rhdf5lib",
        "rhdf5filters"
      ]
    },
    "rhdf5filters": {
      "Package": "rhdf5filters",
      "Version": "1.8.0",
      "Source": "Bioconductor",
      "git_url": "https://git.bioconductor.org/packages/rhdf5filters",
      "git_branch": "RELEASE_3_15",
      "git_last_commit": "b0b588b",
      "git_last_commit_date": "2022-04-26",
      "Hash": "aa885eebeb76d010138fdafe9e91245e",
      "Requirements": [
        "Rhdf5lib"
      ]
    },
    "rlang": {
      "Package": "rlang",
      "Version": "1.0.6",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "4ed1f8336c8d52c3e750adcdc57228a7",
      "Requirements": []
    },
    "rmarkdown": {
      "Package": "rmarkdown",
      "Version": "2.19",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "4e29299e1f4c7eabb0b8365b338adf3c",
      "Requirements": [
        "bslib",
        "evaluate",
        "htmltools",
        "jquerylib",
        "jsonlite",
        "knitr",
        "stringr",
        "tinytex",
        "xfun",
        "yaml"
      ]
    },
    "rprojroot": {
      "Package": "rprojroot",
      "Version": "2.0.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "1de7ab598047a87bba48434ba35d497d",
      "Requirements": []
    },
    "rsample": {
      "Package": "rsample",
      "Version": "1.1.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "cb0c54ebc268ec382be8e4d4a8c34557",
      "Requirements": [
        "dplyr",
        "furrr",
        "generics",
        "glue",
        "pillar",
        "purrr",
        "rlang",
        "slider",
        "tibble",
        "tidyr",
        "tidyselect",
        "vctrs"
      ]
    },
    "rsvd": {
      "Package": "rsvd",
      "Version": "1.0.5",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "b462187d887abc519894874486dbd6fd",
      "Requirements": [
        "Matrix"
      ]
    },
    "s2": {
      "Package": "s2",
      "Version": "1.1.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "328ea3dc4329fc40720456c8e0c75445",
      "Requirements": [
        "Rcpp",
        "wk"
      ]
    },
    "sass": {
      "Package": "sass",
      "Version": "0.4.4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "c76cbac7ca04ce82d8c38e29729987a3",
      "Requirements": [
        "R6",
        "fs",
        "htmltools",
        "rappdirs",
        "rlang"
      ]
    },
    "scales": {
      "Package": "scales",
      "Version": "1.2.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "906cb23d2f1c5680b8ce439b44c6fa63",
      "Requirements": [
        "R6",
        "RColorBrewer",
        "farver",
        "labeling",
        "lifecycle",
        "munsell",
        "rlang",
        "viridisLite"
      ]
    },
    "scattermore": {
      "Package": "scattermore",
      "Version": "0.8",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "77ef398f338597b86a3d6853c585ce38",
      "Requirements": [
        "ggplot2",
        "scales"
      ]
    },
    "sctransform": {
      "Package": "sctransform",
      "Version": "0.3.5",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "e70cffc72eb877eb06e86a20097e93af",
      "Requirements": [
        "MASS",
        "Matrix",
        "Rcpp",
        "RcppArmadillo",
        "dplyr",
        "future",
        "future.apply",
        "ggplot2",
        "gridExtra",
        "magrittr",
        "matrixStats",
        "reshape2",
        "rlang"
      ]
    },
    "scuttle": {
      "Package": "scuttle",
      "Version": "1.6.3",
      "Source": "Bioconductor",
      "git_url": "https://git.bioconductor.org/packages/scuttle",
      "git_branch": "RELEASE_3_15",
      "git_last_commit": "df23680",
      "git_last_commit_date": "2022-08-23",
      "Hash": "30e9a1169ef27c0bc373117773b15bec",
      "Requirements": [
        "BiocGenerics",
        "BiocParallel",
        "DelayedArray",
        "DelayedMatrixStats",
        "GenomicRanges",
        "Matrix",
        "Rcpp",
        "S4Vectors",
        "SingleCellExperiment",
        "SummarizedExperiment",
        "beachmat"
      ]
    },
    "sf": {
      "Package": "sf",
      "Version": "1.0-9",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "8a348490fefb623e7935f405230900a7",
      "Requirements": [
        "DBI",
        "Rcpp",
        "classInt",
        "magrittr",
        "s2",
        "units"
      ]
    },
    "shiny": {
      "Package": "shiny",
      "Version": "1.7.4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "c2eae3d8c670fa9dfa35a12066f4a1d5",
      "Requirements": [
        "R6",
        "bslib",
        "cachem",
        "commonmark",
        "crayon",
        "ellipsis",
        "fastmap",
        "fontawesome",
        "glue",
        "htmltools",
        "httpuv",
        "jsonlite",
        "later",
        "lifecycle",
        "mime",
        "promises",
        "rlang",
        "sourcetools",
        "withr",
        "xtable"
      ]
    },
    "sitmo": {
      "Package": "sitmo",
      "Version": "2.0.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "c956d93f6768a9789edbc13072b70c78",
      "Requirements": [
        "Rcpp"
      ]
    },
    "slam": {
      "Package": "slam",
      "Version": "0.1-50",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "e25793551cbdb843154152e5ee88cbd6",
      "Requirements": []
    },
    "slider": {
      "Package": "slider",
      "Version": "0.3.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "c1c73df260af9e1e3692eb3b8e1ecb88",
      "Requirements": [
        "cli",
        "rlang",
        "vctrs",
        "warp"
      ]
    },
    "snow": {
      "Package": "snow",
      "Version": "0.4-4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "40b74690debd20c57d93d8c246b305d4",
      "Requirements": []
    },
    "sourcetools": {
      "Package": "sourcetools",
      "Version": "0.1.7",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "947e4e02a79effa5d512473e10f41797",
      "Requirements": []
    },
    "sp": {
      "Package": "sp",
      "Version": "1.5-1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "7b6b37e9d8e3295ccd5a73ac6d62db98",
      "Requirements": [
        "lattice"
      ]
    },
    "spData": {
      "Package": "spData",
      "Version": "2.2.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "14ee4bf0dbd2e53f86d161d161e5923e",
      "Requirements": [
        "sp"
      ]
    },
    "sparseMatrixStats": {
      "Package": "sparseMatrixStats",
      "Version": "1.8.0",
      "Source": "Bioconductor",
      "git_url": "https://git.bioconductor.org/packages/sparseMatrixStats",
      "git_branch": "RELEASE_3_15",
      "git_last_commit": "4f1e221",
      "git_last_commit_date": "2022-04-26",
      "Hash": "613693a362fb66eb32dae292b0c9e830",
      "Requirements": [
        "Matrix",
        "MatrixGenerics",
        "Rcpp",
        "matrixStats"
      ]
    },
    "spatial": {
      "Package": "spatial",
      "Version": "7.3-15",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "c23666fdb7789c8a45e65340bb334607",
      "Requirements": []
    },
    "spatstat.data": {
      "Package": "spatstat.data",
      "Version": "3.0-0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "dcca3b7cce62123ad29d553e9c9f4915",
      "Requirements": [
        "Matrix",
        "spatstat.utils"
      ]
    },
    "spatstat.explore": {
      "Package": "spatstat.explore",
      "Version": "3.0-5",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "502fb70c13ef6395ea9f3bd1a7500093",
      "Requirements": [
        "Matrix",
        "abind",
        "goftest",
        "nlme",
        "spatstat.data",
        "spatstat.geom",
        "spatstat.random",
        "spatstat.sparse",
        "spatstat.utils"
      ]
    },
    "spatstat.geom": {
      "Package": "spatstat.geom",
      "Version": "3.0-3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "9f292aca82b76b04086dc96ce55b033e",
      "Requirements": [
        "deldir",
        "polyclip",
        "spatstat.data",
        "spatstat.utils"
      ]
    },
    "spatstat.random": {
      "Package": "spatstat.random",
      "Version": "3.0-1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "83d8358d13b962a402eced1abd381cbc",
      "Requirements": [
        "spatstat.data",
        "spatstat.geom",
        "spatstat.utils"
      ]
    },
    "spatstat.sparse": {
      "Package": "spatstat.sparse",
      "Version": "3.0-0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "b7112033dee68b981804404b37422f7e",
      "Requirements": [
        "Matrix",
        "abind",
        "spatstat.utils",
        "tensor"
      ]
    },
    "spatstat.utils": {
      "Package": "spatstat.utils",
      "Version": "3.0-1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "581b499a03253c6aeeaadf64496c726c",
      "Requirements": []
    },
    "spdep": {
      "Package": "spdep",
      "Version": "1.2-7",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "c46ee2607a20e7079b3c75c6280981fe",
      "Requirements": [
        "boot",
        "deldir",
        "e1071",
        "s2",
        "sf",
        "sp",
        "spData",
        "units"
      ]
    },
    "speedglm": {
      "Package": "speedglm",
      "Version": "0.3-4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "a82eb1b2d58393b1e548982e467026e5",
      "Requirements": [
        "MASS",
        "Matrix"
      ]
    },
    "statmod": {
      "Package": "statmod",
      "Version": "1.4.37",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "2bbd31c2903890c6ef3204470ecfe63b",
      "Requirements": []
    },
    "stringi": {
      "Package": "stringi",
      "Version": "1.7.8",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "a68b980681bcbc84c7a67003fa796bfb",
      "Requirements": []
    },
    "stringr": {
      "Package": "stringr",
      "Version": "1.5.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "671a4d384ae9d32fc47a14e98bfa3dc8",
      "Requirements": [
        "cli",
        "glue",
        "lifecycle",
        "magrittr",
        "rlang",
        "stringi",
        "vctrs"
      ]
    },
    "survival": {
      "Package": "survival",
      "Version": "3.4-0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "04411ae66ab4659230c067c32966fc20",
      "Requirements": [
        "Matrix"
      ]
    },
    "sys": {
      "Package": "sys",
      "Version": "3.4.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "34c16f1ef796057bfa06d3f4ff818a5d",
      "Requirements": []
    },
    "systemfonts": {
      "Package": "systemfonts",
      "Version": "1.0.4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "90b28393209827327de889f49935140a",
      "Requirements": [
        "cpp11"
      ]
    },
    "tensor": {
      "Package": "tensor",
      "Version": "1.5",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "25cfab6cf405c15bccf7e69ec39df090",
      "Requirements": []
    },
    "terra": {
      "Package": "terra",
      "Version": "1.6-47",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "67b7ba63622fbab6820434ac7ac296d6",
      "Requirements": [
        "Rcpp"
      ]
    },
    "testthat": {
      "Package": "testthat",
      "Version": "3.1.6",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "7910146255835c66e9eb272fb215248d",
      "Requirements": [
        "R6",
        "brio",
        "callr",
        "cli",
        "desc",
        "digest",
        "ellipsis",
        "evaluate",
        "jsonlite",
        "lifecycle",
        "magrittr",
        "pkgload",
        "praise",
        "processx",
        "ps",
        "rlang",
        "waldo",
        "withr"
      ]
    },
    "textshaping": {
      "Package": "textshaping",
      "Version": "0.3.6",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "1ab6223d3670fac7143202cb6a2d43d5",
      "Requirements": [
        "cpp11",
        "systemfonts"
      ]
    },
    "tibble": {
      "Package": "tibble",
      "Version": "3.1.8",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "56b6934ef0f8c68225949a8672fe1a8f",
      "Requirements": [
        "fansi",
        "lifecycle",
        "magrittr",
        "pillar",
        "pkgconfig",
        "rlang",
        "vctrs"
      ]
    },
    "tidyr": {
      "Package": "tidyr",
      "Version": "1.2.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "cdb403db0de33ccd1b6f53b83736efa8",
      "Requirements": [
        "cpp11",
        "dplyr",
        "ellipsis",
        "glue",
        "lifecycle",
        "magrittr",
        "purrr",
        "rlang",
        "tibble",
        "tidyselect",
        "vctrs"
      ]
    },
    "tidyselect": {
      "Package": "tidyselect",
      "Version": "1.2.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "79540e5fcd9e0435af547d885f184fd5",
      "Requirements": [
        "cli",
        "glue",
        "lifecycle",
        "rlang",
        "vctrs",
        "withr"
      ]
    },
    "tinytex": {
      "Package": "tinytex",
      "Version": "0.43",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "facc02f3d63ed7dd765513c004c394ce",
      "Requirements": [
        "xfun"
      ]
    },
    "tzdb": {
      "Package": "tzdb",
      "Version": "0.3.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "b2e1cbce7c903eaf23ec05c58e59fb5e",
      "Requirements": [
        "cpp11"
      ]
    },
    "units": {
      "Package": "units",
      "Version": "0.8-1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "81433967f9b34a120a4f5a5a016cd5ed",
      "Requirements": [
        "Rcpp"
      ]
    },
    "utf8": {
      "Package": "utf8",
      "Version": "1.2.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "c9c462b759a5cc844ae25b5942654d13",
      "Requirements": []
    },
    "uuid": {
      "Package": "uuid",
      "Version": "1.1-0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "f1cb46c157d080b729159d407be83496",
      "Requirements": []
    },
    "uwot": {
      "Package": "uwot",
      "Version": "0.1.14",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "c40f4dbc76dd87140045b37a3150a0f1",
      "Requirements": [
        "FNN",
        "Matrix",
        "Rcpp",
        "RcppAnnoy",
        "RcppProgress",
        "dqrng",
        "irlba"
      ]
    },
    "vctrs": {
      "Package": "vctrs",
      "Version": "0.5.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "970324f6572b4fd81db507b5d4062cb0",
      "Requirements": [
        "cli",
        "glue",
        "lifecycle",
        "rlang"
      ]
    },
    "vipor": {
      "Package": "vipor",
      "Version": "0.4.5",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "ea85683da7f2bfa63a98dc6416892591",
      "Requirements": []
    },
    "viridis": {
      "Package": "viridis",
      "Version": "0.6.2",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "ee96aee95a7a563e5496f8991e9fde4b",
      "Requirements": [
        "ggplot2",
        "gridExtra",
        "viridisLite"
      ]
    },
    "viridisLite": {
      "Package": "viridisLite",
      "Version": "0.4.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "62f4b5da3e08d8e5bcba6cac15603f70",
      "Requirements": []
    },
    "vroom": {
      "Package": "vroom",
      "Version": "1.6.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "64f81fdead6e0d250fb041e175d123ab",
      "Requirements": [
        "bit64",
        "cli",
        "cpp11",
        "crayon",
        "glue",
        "hms",
        "lifecycle",
        "progress",
        "rlang",
        "tibble",
        "tidyselect",
        "tzdb",
        "vctrs",
        "withr"
      ]
    },
    "waldo": {
      "Package": "waldo",
      "Version": "0.4.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "035fba89d0c86e2113120f93301b98ad",
      "Requirements": [
        "cli",
        "diffobj",
        "fansi",
        "glue",
        "rematch2",
        "rlang",
        "tibble"
      ]
    },
    "warp": {
      "Package": "warp",
      "Version": "0.2.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "2982481615756e24e79fee95bdc95daa",
      "Requirements": []
    },
    "withr": {
      "Package": "withr",
      "Version": "2.5.0",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "c0e49a9760983e81e55cdd9be92e7182",
      "Requirements": []
    },
    "wk": {
      "Package": "wk",
      "Version": "0.7.1",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "141385279f2cd7faa6a3eccd8d1279dd",
      "Requirements": []
    },
    "xfun": {
      "Package": "xfun",
      "Version": "0.36",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "f5baec54606751aa53ac9c0e05848ed6",
      "Requirements": []
    },
    "xml2": {
      "Package": "xml2",
      "Version": "1.3.3",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "40682ed6a969ea5abfd351eb67833adc",
      "Requirements": []
    },
    "xtable": {
      "Package": "xtable",
      "Version": "1.8-4",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "b8acdf8af494d9ec19ccb2481a9b11c2",
      "Requirements": []
    },
    "yaml": {
      "Package": "yaml",
      "Version": "2.3.6",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "9b570515751dcbae610f29885e025b41",
      "Requirements": []
    },
    "zlibbioc": {
      "Package": "zlibbioc",
      "Version": "1.42.0",
      "Source": "Bioconductor",
      "git_url": "https://git.bioconductor.org/packages/zlibbioc",
      "git_branch": "RELEASE_3_15",
      "git_last_commit": "aa074d7",
      "git_last_commit_date": "2022-04-26",
      "Hash": "908694d02f7332d0576e7c881e572c5a",
      "Requirements": []
    },
    "zoo": {
      "Package": "zoo",
      "Version": "1.8-11",
      "Source": "Repository",
      "Repository": "CRAN",
      "Hash": "874a5b77fe0cfacf2a3450069ae70926",
      "Requirements": [
        "lattice"
      ]
    }
  }
}
